version: '3.4'

x-migrations-image: &migrations-image
  image: shikicinema-migrate
  privileged: true
  build:
    context: .
    dockerfile: Dockerize.Dockerfile
    args:
      baseImage: "${LIQUIBASE_DOCKER_IMAGE}"
  volumes:
    - "./migrations:/migrations"
  entrypoint: [ "dockerize", "-timeout", "20s", "-wait-retry-interval", "3s",
                "-wait", "tcp://shikicinema-db:5432",
                "/entrypoint", "update" ]

x-migrations-envs: &migrations-envs
  LIQUIBASE_USERNAME: postgres
  LIQUIBASE_PASSWORD: postgres
  LIQUIBASE_CHANGELOG: /migrations/index.xml
  LIQUIBASE_OPTS: --defaultSchemaName=public

services:

  shikicinema-db:
    image: "${POSTGRES_DOCKER_IMAGE}"
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shikicinema-dev
      POSTGRES_USER: postgres

  dev-migrations:
    <<: *migrations-image
    environment:
      LIQUIBASE_URL: jdbc:postgresql://shikicinema-db/shikicinema-dev
      <<: *migrations-envs

  test-migrations:
    <<: *migrations-image
    environment:
      LIQUIBASE_URL: jdbc:postgresql://shikicinema-db/shikicinema-test
      <<: *migrations-envs
