version: '3.4'

x-migrations-image: &migrations-image
  image: shikicinema-migrate
  privileged: true
  build:
    context: .
    dockerfile: Dockerize.Dockerfile
    args:
      baseImage: "${LIQUIBASE_DOCKER_IMAGE}"
  volumes:
    - "./migrations:/migrations"
  entrypoint: [ "dockerize", "-timeout", "20s", "-wait-retry-interval", "3s",
                "-wait", "tcp://shikicinema-db:5432",
                "/entrypoint", "update" ]

x-migrations-envs: &migrations-envs
  LIQUIBASE_USERNAME: "${SHIKICINEMA_DB_USER}"
  LIQUIBASE_PASSWORD: "${SHIKICINEMA_DB_PASS}"
  LIQUIBASE_CHANGELOG: /migrations/index.xml
  LIQUIBASE_OPTS: --defaultSchemaName=public

services:

  shikicinema-db:
    image: "${POSTGRES_DOCKER_IMAGE}"
    privileged: true
    restart: always
    ports:
      - "${SHIKICINEMA_DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${SHIKICINEMA_DB_NAME}"
      POSTGRES_USER: "${SHIKICINEMA_DB_USER}"
      POSTGRES_PASSWORD: "${SHIKICINEMA_DB_PASS}"

  dev-migrations:
    <<: *migrations-image
    environment:
      LIQUIBASE_URL: "jdbc:postgresql://shikicinema-db/${SHIKICINEMA_DB_NAME}"
      <<: *migrations-envs
