name: "Backend: Tests, Build and Code style"

on: push

jobs:
  nodejs:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      contents: write

    name: Backend CI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Check code style
        run: npm run lint -w projects/backend

      - name: Check build
        run: npm run build

      - name: Run tests with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          skip-step: install
          test-script: npm test
          working-directory: projects/backend
