name: Tests and Code style

on: push

jobs:
  nodejs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16.13']
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci

      - name: Check code style
        run: npm run lint

      - name: Run tests
        run: npm run test
