name: "Backend: Tests coverage"

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - projects/backend**

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build:types

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          test-script: npm test
          working-directory: projects/backend
